config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resources :bronto_lists do
      collection do
         get 'get_lists'
      end
    end
  end

  resources :orders, :except => [:index, :new, :create, :destroy] do
    patch :subscribe, :on => :member
  end

  get "/account/email_preferences", :to => 'users#email_preferences'

  post "/subscribenewsletter", :to => 'home#subscribenewsletter'
  post "/subscribenewsletters", :to => 'home#subscribenewsletters'
  post "/subscribecampaign", :to => 'home#subscribecampaign'
  post "/subscribecampaign_with_ops", :to => 'home#subscribecampaign_with_ops'

  post "/subscribekeyword", :to => 'home#subscribekeyword'

end

app/models/spree/bronto_list.rb
module Spree
  class BrontoList < ActiveRecord::Base
    has_and_belongs_to_many :users, class_name: "Spree::User", join_table: :spree_bronto_lists_users
    belongs_to :store,  class_name: "Spree::Store"
    validates_presence_of :title
    validates_uniqueness_of :list_id, :message => I18n.t("bronto.validate_unique")
    #validates_numericality_of :list_id

    scope :by_store, lambda { |store| joins(:stores).where("spree_bronto_lists.store_id = ?", store) }

    def validate
      if self.new_record?
        errors.add_to_base I18n.translate("bronto.only_list_can_subscribe_all") if self.subscribe_all_new_users && BrontoList.exists?(["subscribe_all_new_users = ?" , true])
      else
        errors.add_to_base I18n.translate("bronto.only_list_can_subscribe_all") if self.subscribe_all_new_users && BrontoList.exists?(["subscribe_all_new_users = ? AND id <> ?" , true, self.id])
      end
    end
  end

end

app/controllers/spree/admin/bronto_lists_controller.rb
class Spree::Admin::BrontoListsController < Spree::Admin::ResourceController
  before_action :find_stores, only: [:edit, :new]

  def get_lists
    @lists = []
    @list_id = params[:list_id] if params.key? :list_id
    @store_id = params[:store_id] if params.key? :store_id
    @site= Spree::Store.find(@store_id)
    bronto=Bronto.new(Spree::BrontoConfiguration.account[@site.code]['token'])
    et_lists=bronto.read_lists
    #et_list = ET::List.new(Spree::Config.get(:exact_target_user), Spree::Config.get(:exact_target_password))
    et_lists.each do |etl|
      #list = et_list.retrieve_by_id etl[:id]
      @lists << ["#{etl[:name]}", etl[:id]]
    end
    render :partial => "get_lists", :layout => false
  end

  private

  def find_stores
    @stores=Spree::Store.all
  end
end

app/views/spree/admin/bronto_lists/_autocomplete_form.js.erb
<script type='text/template' id='variant_autocomplete_template'>
  <div class='variant-autocomplete-item media'>
    <figure class='variant-image media-left'>
      <span class="thumbnail no-marginb">
        {{#if variant.image }}
          <img src='{{variant.image}}' />
        {{ else }}
          <img src='<%= image_path("noimage/mini.png") %>' />
        {{/if}}
      </span>
    </figure>

    <div class='variant-details media-body'>
      <h5 class="variant-name media-heading">{{variant.name}}</h5>
      {{#if variant.option_values}}
        {{#each variant.option_values}}
          <strong>{{this.option_type_presentation}}:</strong> {{this.presentation}}<br/>
        {{/each}}
      {{/if}}
      <strong><%= Spree.t(:sku) %>:</strong> {{variant.sku}}
    </div>
  </div>
</script>

app/views/spree/admin/bronto_lists/_form.html.erb
<%= render :partial => "spree/admin/bronto_lists/retrieve_lists", :formats => :js %>

    <%= f.field_container :title do %>
    <%= f.label :title, Spree.t("bronto.title") %> <span class="required">*</span><br />
    <%= f.text_field :title, :class => 'fullwidth title'  %>
    <%= f.error_message_on :title %>
  <% end %>

  <div id="lists">
    <%= f.field_container :list_id do %>
      <%= f.label :list_id, Spree.t("bronto.list_id") %> <span class="required">*</span><br />
      <%= f.text_field :list_id %>
      <%= button_tag Spree.t("bronto.retrieve_from_bronto"), :id => "retrieve_bronto_list", :type => "button" %>
      <%= f.error_message_on :list_id %>
    <% end %>
  </div>

  <%= f.field_container :visible do %>
    <%= f.label :visible, Spree.t("bronto.visible") %> <span class="required">*</span><br />

      <%= f.radio_button(:visible, true ) %>
      <%= Spree.t("yes") %>

      <%= f.radio_button(:visible, false ) %>
      <%= Spree.t("no") %>

      <%= f.error_message_on :visible %>
  <% end %>

  <%= f.field_container :subscribe_all_new_users do %>
    <%= f.label :subscribe_all_new_users, Spree.t("bronto.subscribe_all_new_users") %> <span class="required">*</span><br />

      <%= f.radio_button(:subscribe_all_new_users, true ) %>
      <%= Spree.t("yes") %>

      <%= f.radio_button(:subscribe_all_new_users, false ) %>
      <%= Spree.t("no") %>

      <%= f.error_message_on :subscribe_all_new_users %>
  <% end %>


  <%= f.field_container :store_id do %>
      <%= f.label :store_id, Spree.t("bronto.store_id") %> <span class="required">*</span><br />

      <%= f.collection_select :store_id, @stores, :id, :name, {}, { :multiple => false, :class => "select2" } %>

      <%= f.error_message_on :store_id %>
  <% end %>

app/views/spree/admin/bronto_lists/_get_lists.html.erb
<%= select_tag 'bronto_list[list_id]', options_for_select(@lists, @list_id) -%>

app/views/spree/admin/bronto_lists/_get_lists.js.erb
$('#bronto_list_list_id').replaceWith('<%= escape_javascript(render partial: 'spree/admin/bronto_lists/get_lists', formats: [:html], handlers: [:erb]) %>');

app/views/spree/admin/bronto_lists/_retrieve_lists.js.erb
<script type="text/javascript">
$(document).ready(
        function() {
          $('#retrieve_bronto_list').click(function () {
            $.getScript('<%= get_lists_admin_bronto_lists_path %>.js?list_id=' + $('#bronto_list_list_id').val() + '&store_id=' + $('#bronto_list_store_id').val())
          });
          $('#bronto_list_store_id').change(function () {
            $.getScript('<%= get_lists_admin_bronto_lists_path %>.js?list_id=' + $('#bronto_list_list_id').val() + '&store_id=' + $('#bronto_list_store_id').val())
          });
        });
</script>

app/views/spree/admin/bronto_lists/edit.html.erb
<h1><%= Spree.t("bronto.editing") %></h1>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @bronto_list } %>
<%= form_for(@bronto_list, :url => object_url, :html => { :method => :put }) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <p>
    <%=submit_tag Spree.t("update")%>
  </p>
<% end %>

app/views/spree/admin/bronto_lists/index.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to Spree.t("bronto.new_list"), new_object_url, :icon => 'add'  %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= Spree.t("exact_target.lists") %></h1>

<table class="index">
  <thead data-hook="admin_bronto_lists_index_headers">
      <th><%= Spree.t("bronto.title") %></th>
      <th><%= Spree.t("bronto.list_id") %></th>
      <th><%= Spree.t("bronto.subscribe_all_new_users") %></th>
      <th><%= Spree.t("bronto.visible") %></th>
    <th data-hook="admin_bronto_lists_index_header_actions"></th>
  </thead>
  <tbody>
    <% @bronto_lists.each do |bronto_list|%>
      <tr data-hook="admin_exact_target_lists_index_rows" id="<%= dom_id bronto_list %>">
        <%- locals = {:exact_target_list => bronto_list} -%>

          <td width="140px"><%= bronto_list.title %></td>
          <td width="120px"><%= bronto_list.list_id %></td>
          <td width="40px"><%= bronto_list.subscribe_all_new_users.to_s.titleize %></td>
          <td width="40px"><%= bronto_list.visible.to_s.titleize %></td>
        <td data-hook="admin_bronto_lists_index_row_actions" width="140px">
            <%= link_to_edit bronto_list %> &nbsp;
            <%= link_to_delete bronto_list %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/bronto_lists/new.html.erb
<h1><%= Spree.t("bronto.new_list") %></h1>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @bronto_list } %>

<%= form_for [:admin,@bronto_list], :html => { :multipart => true }  do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <p>
    <%= submit_tag Spree.t("create") %>
  </p>
<% end %>